### PR TITLE
clarify license

### PR DESCRIPTION
**Pull request by cskiraly**
Clarify terms of license applied on this repository

### CODE REVIEW

**Comment by dryajov** [comment]
Why are we mentioning beacon chain in the license?

**Comment by cskiraly** [comment]
> Why are we mentioning beacon chain in the license?

Good catch, thanks! I've assumed people use the original text, but clearly it wasn't the case. Let me replace it with the real one.

**Comment by cskiraly** [comment]
fixed. Merging soon if no other comments.

**Comment by leobago** [comment]
LGTM

**Pull request merged**
